version: "3"
services:
  z-mysql:
    #image: mysql:5.7.15
    image: mysql:8.0.27
    hostname: z-mysql
    networks:
      - z-net
    ports:
      - "3306:3306"
      #    restart: always
    volumes:
      - "${HOME}/docker/mysql/data:/var/lib/mysql"
      - "${HOME}/docker/mysql/config:/etc/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    command: [                        #使用 command 可以覆盖容器启动后默认执行的命令
      '--character-set-server=utf8mb4',            #设置数据库表的数据集
      '--collation-server=utf8mb4_unicode_ci',    #设置数据库表的数据集
      '--default-time-zone=+8:00'                    #设置mysql数据库的 时区问题！！！！ 而不是设置容器的时区问题！！！！
    ]
#  z-redis:
#    image: redis
#    hostname: z-redis
#    networks:
#      - z-net
#    ports:
#      - "6379:6379"
#      #    restart: always
#    volumes:
#      - "${HOME}/docker/redis/redis.conf:/etc/redis/redis.conf"
#      - "${HOME}/docker/redis/data:/data"
#    command:
#      redis-server /etc/redis/redis.conf --appendonly yes
networks:
  z-net:
    driver: bridge
