--liquibase formatted sql
--changeset zzw:00002_init_acct_rebuild

-- =====================================================================
-- 科目体系地基重建: 引入多租户(tenant_id)隔离 + balance_dir + 唯一约束
-- ---------------------------------------------------------------------
-- 背景:
--   原 00000_init.sql 建的 acct_account_cls 缺 tenant_id / balance_dir 列,
--   且 acct_vou_detail 只存在于从未被 liquibase 加载的死文件中.
--   导致多租户隔离与余额方向完全失效.
--
-- 策略: 清空重初始化(已确认决策). 直接 DROP 两张 acct 表后用正确结构重建.
--   - acct_account_cls: 增加 tenant_id, balance_dir, (tenant_id, code) 唯一约束
--   - 预设科目写入 tenant_id='__template__' 作为"科目模板",
--     新家庭注册时由 TenantCreatedEvent 监听器复制一份到自身 tenant_id 下.
--   - balance_dir: 资产/支出=1(借), 负债/收入=-1(贷); 二级沿用父方向.
--   - 新增账户类科目(微信/支付宝/花呗), 信用卡归负债(贷).
-- =====================================================================

-- 1. 清空重初始化: 删除旧表(含数据)
DROP TABLE IF EXISTS acct_vou_detail;
DROP TABLE IF EXISTS acct_account_cls;

-- 2. 会计科目表: 增加 tenant_id, balance_dir 列, (tenant_id, code) 唯一约束
CREATE TABLE acct_account_cls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by varchar(50) NULL,
    created_date timestamp NULL,
    last_modified_by varchar(50) NULL,
    last_modified_date timestamp NULL,
    set_year varchar(4) NULL,
    code varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    balance_dir int NULL,
    is_enabled int DEFAULT 1,
    remark varchar(255) NULL,
    is_standard int DEFAULT 0,
    parent_id bigint NULL,
    level_no int NULL,
    is_leaf int DEFAULT 1,
    icon varchar(50) NULL,
    order_num int DEFAULT 0,
    tenant_id varchar(50) NOT NULL DEFAULT '__template__',
    CONSTRAINT uk_acct_cls_tenant_code UNIQUE (tenant_id, code)
);

COMMENT ON COLUMN acct_account_cls.set_year IS '核算年度';
COMMENT ON COLUMN acct_account_cls.code IS '科目代码(家庭内唯一)';
COMMENT ON COLUMN acct_account_cls.name IS '科目名称';
COMMENT ON COLUMN acct_account_cls.balance_dir IS '余额方向：1=借方, -1=贷方';
COMMENT ON COLUMN acct_account_cls.is_enabled IS '是否启用：0=否, 1=是';
COMMENT ON COLUMN acct_account_cls.remark IS '备注';
COMMENT ON COLUMN acct_account_cls.is_standard IS '是否预设(模板)：1=预设不可删, 0=用户自定义';
COMMENT ON COLUMN acct_account_cls.parent_id IS '上级科目ID';
COMMENT ON COLUMN acct_account_cls.level_no IS '级次';
COMMENT ON COLUMN acct_account_cls.is_leaf IS '是否末级：0=否, 1=是';
COMMENT ON COLUMN acct_account_cls.icon IS '图标';
COMMENT ON COLUMN acct_account_cls.order_num IS '排序号';
COMMENT ON COLUMN acct_account_cls.tenant_id IS '租户ID(家庭号), __template__ 为预设模板';

-- 3. 凭证分录表: 补 tenant_id, 索引
CREATE TABLE acct_vou_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by varchar(50) NULL,
    created_date timestamp NULL,
    last_modified_by varchar(50) NULL,
    last_modified_date timestamp NULL,
    voucher_no varchar(50) NOT NULL,
    acct_cls_code varchar(50) NOT NULL,
    acct_cls_name varchar(100) NULL,
    amt decimal(18,2) NOT NULL,
    dr_cr int NOT NULL,
    remark varchar(255) NULL,
    tenant_id varchar(50) NULL
);
CREATE INDEX idx_vou_detail_voucher_no ON acct_vou_detail (voucher_no);
CREATE INDEX idx_vou_detail_acct_cls_code ON acct_vou_detail (acct_cls_code);
CREATE INDEX idx_vou_detail_created_date ON acct_vou_detail (created_date);
CREATE INDEX idx_vou_detail_tenant ON acct_vou_detail (tenant_id);

COMMENT ON COLUMN acct_vou_detail.voucher_no IS '凭证号';
COMMENT ON COLUMN acct_vou_detail.acct_cls_code IS '科目代码';
COMMENT ON COLUMN acct_vou_detail.acct_cls_name IS '科目名称（冗余字段）';
COMMENT ON COLUMN acct_vou_detail.amt IS '金额';
COMMENT ON COLUMN acct_vou_detail.dr_cr IS '借贷方向：1=借方, -1=贷方';
COMMENT ON COLUMN acct_vou_detail.remark IS '备注';
COMMENT ON COLUMN acct_vou_detail.tenant_id IS '租户ID(家庭号)';

-- 4. 预设科目模板 (tenant_id = '__template__')
--    一级: 资产/负债/收入/支出 (is_standard=1, is_leaf=0)
INSERT INTO acct_account_cls (id, code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, set_year, tenant_id)
VALUES
    (1, '001', '资产', 1, 1, 0, 1, 0, 1, '2024', '__template__'),
    (2, '002', '负债', -1, 1, 0, 1, 0, 2, '2024', '__template__'),
    (3, '003', '收入', -1, 1, 0, 1, 0, 3, '2024', '__template__'),
    (4, '004', '支出', 1, 1, 0, 1, 0, 4, '2024', '__template__');

--    资产类二级 (账户 + 资产, balance_dir=1)
INSERT INTO acct_account_cls (id, code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, set_year, tenant_id)
VALUES
    (6, '001001', '现金', 1, 1, 1, 2, 1, 1, '2024', '__template__'),
    (7, '001002', '银行存款', 1, 1, 1, 2, 1, 2, '2024', '__template__'),
    (8, '001003', '微信', 1, 1, 1, 2, 1, 3, '2024', '__template__'),
    (9, '001004', '支付宝', 1, 1, 1, 2, 1, 4, '2024', '__template__'),
    (10, '001005', '花呗', 1, 1, 1, 2, 1, 5, '2024', '__template__'),
    (11, '001006', '投资', 1, 1, 1, 2, 1, 6, '2024', '__template__'),
    (12, '001007', '固定资产', 1, 1, 1, 2, 1, 7, '2024', '__template__'),
    (13, '001008', '其他资产', 1, 1, 1, 2, 1, 8, '2024', '__template__');

--    负债类二级 (balance_dir=-1; 信用卡归负债)
INSERT INTO acct_account_cls (id, code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, set_year, tenant_id)
VALUES
    (14, '002001', '贷款', -1, 1, 2, 2, 1, 1, '2024', '__template__'),
    (15, '002002', '信用卡', -1, 1, 2, 2, 1, 2, '2024', '__template__'),
    (16, '002003', '抵押', -1, 1, 2, 2, 1, 3, '2024', '__template__'),
    (17, '002004', '其他负债', -1, 1, 2, 2, 1, 4, '2024', '__template__');

--    收入类二级 (balance_dir=-1)
INSERT INTO acct_account_cls (id, code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, set_year, tenant_id)
VALUES
    (18, '003001', '工资', -1, 1, 3, 2, 1, 1, '2024', '__template__'),
    (19, '003002', '投资', -1, 1, 3, 2, 1, 2, '2024', '__template__'),
    (20, '003003', '其他收入', -1, 1, 3, 2, 1, 3, '2024', '__template__');

--    支出类二级 (balance_dir=1)
INSERT INTO acct_account_cls (id, code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, set_year, tenant_id)
VALUES
    (21, '004001', '衣服', 1, 1, 4, 2, 1, 1, '2024', '__template__'),
    (22, '004002', '食品', 1, 1, 4, 2, 1, 2, '2024', '__template__'),
    (23, '004003', '住房', 1, 1, 4, 2, 1, 3, '2024', '__template__'),
    (24, '004004', '交通', 1, 1, 4, 2, 1, 4, '2024', '__template__'),
    (25, '004005', '娱乐', 1, 1, 4, 2, 1, 5, '2024', '__template__'),
    (26, '004006', '健身', 1, 1, 4, 2, 1, 6, '2024', '__template__'),
    (27, '004007', '保险', 1, 1, 4, 2, 1, 7, '2024', '__template__'),
    (28, '004008', '学习提升', 1, 1, 4, 2, 1, 8, '2024', '__template__'),
    (29, '004009', '日常用品', 1, 1, 4, 2, 1, 9, '2024', '__template__'),
    (30, '004010', '其他费用', 1, 1, 4, 2, 1, 10, '2024', '__template__');

-- 5. 预设模板用了固定 id, 重置序列避免后续自增冲突
SELECT setval(pg_get_serial_sequence('acct_account_cls','id'), (SELECT COALESCE(MAX(id),0)+1 FROM acct_account_cls), false);

-- 6. 为内置 admin 用户(id=1)预置一份家庭科目(tenant_id='fam_1'), 使其开箱即用.
--    admin 的 tenant_id 由 00000_init.sql 维护, 这里同步补上.
UPDATE sys_user SET tenant_id = 'fam_1' WHERE id = 1 AND tenant_id IS NULL;

-- 复制模板到 fam_1 (一级 parentId 重置为 0, 二级指向新一级 id)
INSERT INTO acct_account_cls (code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, set_year, tenant_id)
SELECT code, name, balance_dir, is_standard, 0, level_no, is_leaf, order_num, set_year, 'fam_1'
FROM acct_account_cls WHERE tenant_id = '__template__' AND level_no = 1;

-- 二级科目: parent_id 指向 fam_1 下对应的一级科目(按 code 关联)
INSERT INTO acct_account_cls (code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, set_year, tenant_id)
SELECT t.code, t.name, t.balance_dir, t.is_standard,
       p.id, t.level_no, t.is_leaf, t.order_num, t.set_year, 'fam_1'
FROM acct_account_cls t
JOIN acct_account_cls tp ON t.parent_id = tp.id AND tp.tenant_id = '__template__'
JOIN acct_account_cls p ON p.tenant_id = 'fam_1' AND p.code = tp.code
WHERE t.tenant_id = '__template__' AND t.level_no = 2;
