--liquibase formatted sql
--changeset zzw:00001_init_admin_menu

-- 给 ROLE_ADMIN(id=1) 关联 sys_menu 全部菜单, 解决 admin 登录后所有菜单/按钮权限缺失导致
-- getMenusRoute 等接口被 @PreAuthorize(hasAuthority(...)) 拦截 403 (AuthorizationDeniedException) 的问题.
-- 权限链路: sys_user_authority(role_id) -> sys_role_menu(role_id -> menu_id) -> sys_menu.permission_code

-- sys_role_menu 由 JPA(ddl-auto:update) 自动建表, liquibase 执行可能早于 JPA 初始化,
-- 所以这里显式保证表存在, 幂等.
CREATE TABLE IF NOT EXISTS sys_role_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by varchar(50) NULL,
    created_date timestamp NULL,
    last_modified_by varchar(50) NULL,
    last_modified_date timestamp NULL,
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL
);

-- 先清掉 ROLE_ADMIN 旧的关联, 避免重复执行时主键/重复数据问题
DELETE FROM sys_role_menu WHERE role_id = 1;

-- 把 sys_menu 全部菜单关联给 ROLE_ADMIN, permission_code 为空的一并关联也无妨
INSERT INTO sys_role_menu (created_by, created_date, last_modified_by, last_modified_date, role_id, menu_id)
SELECT 'system', NOW(), 'system', NOW(), 1, m.id FROM sys_menu m;

-- id 用了自增, 关联完重置序列避免后续自增冲突
SELECT setval(pg_get_serial_sequence('sys_role_menu','id'), (SELECT COALESCE(MAX(id),0)+1 FROM sys_role_menu), false);
