--liquibase formatted sql
--changeset zzw:acct_002_init_voucher_detail

-- 凭证分录表
CREATE TABLE IF NOT EXISTS acct_vou_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by varchar(50) NULL,
    created_date timestamp NULL,
    last_modified_by varchar(50) NULL,
    last_modified_date timestamp NULL,
    voucher_no varchar(50) NOT NULL,
    acct_cls_code varchar(50) NOT NULL,
    acct_cls_name varchar(100) NULL,
    amt decimal(18,2) NOT NULL,
    dr_cr int NOT NULL,
    remark varchar(255) NULL,
    tenant_id varchar(50) NULL
);
CREATE INDEX IF NOT EXISTS idx_vou_detail_voucher_no ON acct_vou_detail (voucher_no);
CREATE INDEX IF NOT EXISTS idx_vou_detail_acct_cls_code ON acct_vou_detail (acct_cls_code);
CREATE INDEX IF NOT EXISTS idx_vou_detail_created_date ON acct_vou_detail (created_date);

COMMENT ON COLUMN acct_vou_detail.voucher_no IS '凭证号';
COMMENT ON COLUMN acct_vou_detail.acct_cls_code IS '科目代码';
COMMENT ON COLUMN acct_vou_detail.acct_cls_name IS '科目名称（冗余字段）';
COMMENT ON COLUMN acct_vou_detail.amt IS '金额';
COMMENT ON COLUMN acct_vou_detail.dr_cr IS '借贷方向：1=借方, -1=贷方';
COMMENT ON COLUMN acct_vou_detail.remark IS '备注';
COMMENT ON COLUMN acct_vou_detail.tenant_id IS '租户ID';

-- 余额汇总表（预留给后续性能优化）
CREATE TABLE IF NOT EXISTS acct_bal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by varchar(50) NULL,
    created_date timestamp NULL,
    last_modified_by varchar(50) NULL,
    last_modified_date timestamp NULL,
    acct_cls_code varchar(50) NOT NULL,
    bal_amt decimal(18,2) DEFAULT 0,
    bal_date date NOT NULL,
    tenant_id varchar(50) NULL,
    CONSTRAINT uk_bal_code_date UNIQUE (acct_cls_code, bal_date)
);
CREATE INDEX IF NOT EXISTS idx_bal_acct_cls_code ON acct_bal (acct_cls_code);
CREATE INDEX IF NOT EXISTS idx_bal_date ON acct_bal (bal_date);

COMMENT ON COLUMN acct_bal.acct_cls_code IS '科目代码';
COMMENT ON COLUMN acct_bal.bal_amt IS '期末余额';
COMMENT ON COLUMN acct_bal.bal_date IS '余额日期';
COMMENT ON COLUMN acct_bal.tenant_id IS '租户ID';

-- 额度控制表（预留）
CREATE TABLE IF NOT EXISTS acct_ctrl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by varchar(50) NULL,
    created_date timestamp NULL,
    last_modified_by varchar(50) NULL,
    last_modified_date timestamp NULL,
    acct_cls_code varchar(50) NOT NULL,
    ctrl_amt decimal(18,2) NOT NULL,
    used_amt decimal(18,2) DEFAULT 0,
    period_type varchar(20) NULL,
    period_value varchar(20) NULL,
    tenant_id varchar(50) NULL,
    CONSTRAINT uk_ctrl_code_period UNIQUE (acct_cls_code, period_type, period_value)
);
CREATE INDEX IF NOT EXISTS idx_ctrl_acct_cls_code ON acct_ctrl (acct_cls_code);

COMMENT ON COLUMN acct_ctrl.acct_cls_code IS '科目代码';
COMMENT ON COLUMN acct_ctrl.ctrl_amt IS '额度上限';
COMMENT ON COLUMN acct_ctrl.used_amt IS '已使用额度';
COMMENT ON COLUMN acct_ctrl.period_type IS '周期类型：month/quarter/year';
COMMENT ON COLUMN acct_ctrl.period_value IS '周期值';
COMMENT ON COLUMN acct_ctrl.tenant_id IS '租户ID';
