--liquibase formatted sql
--changeset zzw:acct_001_init_account_cls

-- 科目表初始化
CREATE TABLE IF NOT EXISTS acct_account_cls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by varchar(50) NULL,
    created_date timestamp NULL,
    last_modified_by varchar(50) NULL,
    last_modified_date timestamp NULL,
    set_year varchar(4) NULL,
    code varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    balance_dir int NULL,
    is_enabled int DEFAULT 1,
    remark varchar(255) NULL,
    is_standard int DEFAULT 0,
    parent_id bigint NULL,
    level_no int NULL,
    is_leaf int DEFAULT 1,
    icon varchar(50) NULL,
    order_num int DEFAULT 0,
    tenant_id varchar(50) NULL,
    CONSTRAINT uk_acct_cls_code UNIQUE (code)
);

COMMENT ON COLUMN acct_account_cls.set_year IS '核算年度';
COMMENT ON COLUMN acct_account_cls.code IS '科目代码';
COMMENT ON COLUMN acct_account_cls.name IS '科目名称';
COMMENT ON COLUMN acct_account_cls.balance_dir IS '余额方向：1=借方, -1=贷方';
COMMENT ON COLUMN acct_account_cls.is_enabled IS '是否启用：0=否, 1=是';
COMMENT ON COLUMN acct_account_cls.remark IS '备注';
COMMENT ON COLUMN acct_account_cls.is_standard IS '是否标准：0=否, 1=是';
COMMENT ON COLUMN acct_account_cls.parent_id IS '上级科目ID';
COMMENT ON COLUMN acct_account_cls.level_no IS '级次';
COMMENT ON COLUMN acct_account_cls.is_leaf IS '是否末级：0=否, 1=是';
COMMENT ON COLUMN acct_account_cls.icon IS '图标';
COMMENT ON COLUMN acct_account_cls.order_num IS '排序号';
COMMENT ON COLUMN acct_account_cls.tenant_id IS '租户ID';

-- 插入一级科目
INSERT INTO acct_account_cls (code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, tenant_id)
VALUES
    ('001', '资产', 1, 1, NULL, 1, 0, 1, 'default'),
    ('002', '负债', -1, 1, NULL, 1, 0, 2, 'default'),
    ('003', '收入', -1, 1, NULL, 1, 0, 3, 'default'),
    ('004', '支出', 1, 1, NULL, 1, 0, 4, 'default');

-- 插入二级科目（资产类）
INSERT INTO acct_account_cls (code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, tenant_id)
SELECT '001001', '银行存款', 1, 1, id, 2, 1, 1, 'default' FROM acct_account_cls WHERE code = '001';

INSERT INTO acct_account_cls (code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, tenant_id)
SELECT '001002', '现金', 1, 1, id, 2, 1, 2, 'default' FROM acct_account_cls WHERE code = '001';

-- 插入二级科目（负债类）
INSERT INTO acct_account_cls (code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, tenant_id)
SELECT '002001', '信用卡', -1, 1, id, 2, 1, 1, 'default' FROM acct_account_cls WHERE code = '002';

-- 插入二级科目（收入类）
INSERT INTO acct_account_cls (code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, tenant_id)
SELECT '003001', '工资收入', -1, 1, id, 2, 1, 1, 'default' FROM acct_account_cls WHERE code = '003';

INSERT INTO acct_account_cls (code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, tenant_id)
SELECT '003002', '理财收入', -1, 1, id, 2, 1, 2, 'default' FROM acct_account_cls WHERE code = '003';

-- 插入二级科目（支出类）
INSERT INTO acct_account_cls (code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, tenant_id)
SELECT '004001', '餐饮支出', 1, 1, id, 2, 1, 1, 'default' FROM acct_account_cls WHERE code = '004';

INSERT INTO acct_account_cls (code, name, balance_dir, is_standard, parent_id, level_no, is_leaf, order_num, tenant_id)
SELECT '004002', '交通支出', 1, 1, id, 2, 1, 2, 'default' FROM acct_account_cls WHERE code = '004';
